# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v30nBCuyvU8D7q9sozRVUCHExDVopz7_
"""

# string  in python

s = "asdfghkmnbv"
print(s[1])
print(len(s))

def str(s):
  if len(s)==0:
    return
  print (s[0])
  str(s[1:])

str("asdfg")

def str (s):
  if len(s) == 0:
    return
  str(s[1:])
  print(s[0], end=" ")



str("aman")

# s1 = "aman raja khaja"
# s2 = "a"

def count(s1,s2):
  if s2  :
    return count+1
    print(count)

s1 = "aman raja khaja"
s2 = "a,"

def ps (s1,s2):
  if len(s1)==0:
    return 0
  return 1+ps(s1[1:],s2)

ps(s1,s2)

s1 = "aman raja khaja"
s2 = "aeiou"

def vo(s1,s2):





c=0
for i in s1 :
  if s2 == i:
   c+=1

print(c)

s1 = "aman raja khaja"
s2 = "ja"

def mg(s1,s2):

#  we can add two string
print("ab"+"bc")

num = 512
num = str(num)  # type coversion
num[0]
int(num[0])+int(num[1])+int(num[2]) #ahain type conversion

# by the help of loop
num = 513
num = str(num)
sum = 0
for i in num:
  sum  = sum + int(i)
print(sum)

# Edit an delete
c = "helo"
c [0]= i # there is no any  change  in the string
print(c)

"aman"*0  # multiply in string
"aman"*2

# check operators
"aman">"naman"

"nitin "<"jatin"

"sumit"

l = [ "nitin","jaytin","aman","sonu","tanisk","adrash"]

l2 = []
for i in l:
  count = 0
  for j in i:
    count+=1
  l2.append(count)
print(l2)

l3=[]
for i in l2:
  if i not in l3:
    l3.append(i)
print(l3)

l = [ "nitin","jaytin","aman","sonu","tanisk","adrash"]
for name in l:
 l2.append(len(name))
print(l2)
l3 = set(l2)
l3

a = 5
b = a
b=2
print(a,b)





